import { z } from 'zod';
import { TradeSideSchema } from './domain.js';

// ============================================================
// Trade (NCN-19)
// Append-only ledger entry. One row per fill.
// Stored in Prisma `Trade` table (one-to-many from Account).
//
// `automationItemId` is the source discriminator:
//   - defined  → fill was triggered by an AutomationItem
//   - undefined → fill was manual (post NCN-16 manual endpoint)
// ============================================================

export const TradeSchema = z
  .object({
    id: z.string().min(1),
    accountId: z.string().min(1),
    symbol: z.string().min(1),
    side: TradeSideSchema,
    price: z.number().finite().nonnegative(),
    qty: z.number().finite().positive(),
    /**
     * Fees paid on this fill, in the same quote currency as `price`.
     * Optional — defaults to 0 when absent so legacy rows (and trades
     * posted through broker integrations that don't break out fees)
     * continue to compute PnL correctly.
     */
    fee: z.number().finite().nonnegative().optional(),
    /** ISO timestamp of execution */
    timestamp: z.string(),
    /** Set when generated by an AutomationItem; absent trades are manual */
    automationItemId: z.string().min(1).optional(),
  })
  .strict();

export type Trade = z.infer<typeof TradeSchema>;
