import { z } from 'zod';
import { TradeSideSchema } from './domain.js';

// ============================================================
// Trade (NCN-19)
// Append-only ledger entry. One row per fill.
// Stored in Prisma `Trade` table (one-to-many from Account).
//
// `automationItemId` is the source discriminator:
//   - defined  → fill was triggered by an AutomationItem
//   - undefined → fill was manual (post NCN-16 manual endpoint)
// ============================================================

export const TradeSchema = z
  .object({
    id: z.string().min(1),
    accountId: z.string().min(1),
    symbol: z.string().min(1),
    side: TradeSideSchema,
    price: z.number().finite().nonnegative(),
    qty: z.number().finite().positive(),
    /** ISO timestamp of execution */
    timestamp: z.string(),
    /** Set when generated by an AutomationItem; absent trades are manual */
    automationItemId: z.string().min(1).optional(),
  })
  .strict();

export type Trade = z.infer<typeof TradeSchema>;
