export const Timeframe = {
  ONE_MINUTE: '1m',
  FIVE_MINUTES: '5m',
  FIFTEEN_MINUTES: '15m',
  ONE_HOUR: '1h',
  FOUR_HOURS: '4h',
  ONE_DAY: '1d',
  TWO_DAYS: '2d',
  THREE_DAYS: '3d',
  FOUR_DAYS: '4d',
  FIVE_DAYS: '5d',
  SIX_DAYS: '6d',
  ONE_WEEK: '1w',
} as const;

export type Timeframe = (typeof Timeframe)[keyof typeof Timeframe];

export const Signal = {
  BUY: 'BUY',
  SELL: 'SELL',
  HOLD: 'HOLD',
} as const;

export type Signal = (typeof Signal)[keyof typeof Signal];

export interface Candle {
  openTime: number;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  closeTime: number;
}

export interface CandleWithIndicators extends Candle {
  rsi: number | null;
  emaRsi: number | null;
  wmaRsi: number | null;
}

export interface SupportResistanceLevel {
  price: number;
  touches: number;
  kind: 'support' | 'resistance';
  lastTouchTime: number;
}

export interface SupportResistanceResult {
  levels: SupportResistanceLevel[];
}

// ============================================================
// NCN-5: Core domain schema
// Contract-only — consumed by the Account, PnL and Automation
// modules. Implementation comes with those epics.
// ============================================================

export const AccountType = {
  REAL: 'real',
  DEMO: 'demo',
} as const;
export type AccountType = (typeof AccountType)[keyof typeof AccountType];

export const AccountStatus = {
  ACTIVE: 'active',
  DISABLED: 'disabled',
} as const;
export type AccountStatus = (typeof AccountStatus)[keyof typeof AccountStatus];

/** Trading account — real (broker/exchange) or demo (paper money) */
export interface Account {
  id: string;
  type: AccountType;
  /** Quote-currency balance available for trading */
  balance: number;
  status: AccountStatus;
  /** ISO timestamps */
  createdAt: string;
  updatedAt: string;
}

export const TradeSide = {
  BUY: 'buy',
  SELL: 'sell',
} as const;
export type TradeSide = (typeof TradeSide)[keyof typeof TradeSide];

/** Executed trade — append-only ledger entry, never mutated */
export interface Trade {
  id: string;
  accountId: string;
  symbol: string;
  side: TradeSide;
  price: number;
  qty: number;
  /** ISO timestamp of execution */
  timestamp: string;
  /** Set when generated by an AutomationItem; absent trades are manual */
  automationItemId?: string;
}

/** Open position per account + symbol, carrying unrealized state */
export interface Position {
  id: string;
  accountId: string;
  symbol: string;
  side: TradeSide;
  /** Remaining size (absolute value) */
  qty: number;
  /** Volume-weighted average entry price of the position */
  avgEntryPrice: number;
  /** Mark-to-market PnL against the latest price; null when no mark price is available */
  unrealizedPnl: number | null;
  openedAt: string;
  updatedAt: string;
}

/**
 * Automation input provider — the event source that can trigger the item.
 * Kinds follow the Automation epic's provider backlog:
 * wave detection (RSI/EMA crossover), support/resistance touch, time trigger.
 */
export type AutomationInput =
  | { kind: 'rsiEmaWave'; symbol: string; interval: Timeframe }
  | {
      kind: 'supportResistance';
      symbol: string;
      interval: Timeframe;
      /** Minimum cluster touches for a level to count as touched */
      minTouches: number;
    }
  | { kind: 'time'; cron: string };

export const AutomationConditionOperator = {
  GT: '>',
  LT: '<',
  GTE: '>=',
  LTE: '<=',
  EQ: '==',
  NEQ: '!=',
} as const;
export type AutomationConditionOperator =
  (typeof AutomationConditionOperator)[keyof typeof AutomationConditionOperator];

/** Single predicate over a field exposed by the input provider, e.g. `rsi.value` */
export interface AutomationCondition {
  field: string;
  operator: AutomationConditionOperator;
  value: number | string | boolean;
}

/** Order placed through the Order/Execution abstraction when the item triggers */
export type AutomationAction =
  | { kind: 'buy'; symbol: string; qty: number }
  | { kind: 'sell'; symbol: string; qty: number };

/** What the item emits besides the action itself */
export type AutomationOutput =
  | { kind: 'none' }
  | { kind: 'notify'; message: string };

export const AutomationItemStatus = {
  ENABLED: 'enabled',
  DISABLED: 'disabled',
  PAUSED: 'paused',
} as const;
export type AutomationItemStatus =
  (typeof AutomationItemStatus)[keyof typeof AutomationItemStatus];

/** User-configurable automation: input → conditions (AND) → action + output */
export interface AutomationItem {
  id: string;
  name: string;
  input: AutomationInput;
  /** All conditions must hold (AND) for the item to trigger */
  conditions: AutomationCondition[];
  action: AutomationAction;
  output: AutomationOutput;
  status: AutomationItemStatus;
  createdAt: string;
  updatedAt: string;
}

export interface RsiResult {
  value: number | null;
}

export interface EmaCrossoverResult {
  fast: number | null;
  slow: number | null;
  crossed: 'up' | 'down' | null;
}

export interface WmaResult {
  value: number | null;
}

export interface SignalDecision {
  symbol: string;
  interval: Timeframe;
  signal: Signal;
  price: number;
  evaluatedAt: string;
  indicators: {
    rsi: RsiResult;
    emaCrossover: EmaCrossoverResult;
    wma: WmaResult;
  };
  reason: string;
}
